"""empty message

Revision ID: 719fa20a07aa
Revises: d53f71bd53fe
Create Date: 2021-04-19 07:43:06.234766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719fa20a07aa'
down_revision = 'd53f71bd53fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
