"""empty message

Revision ID: 9133002eb7e5
Revises: 36c35dbc47ad
Create Date: 2021-04-26 23:38:46.849513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9133002eb7e5'
down_revision = '36c35dbc47ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
